# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'gallery_section',
                'verbose_name_plural': 'gallery_sections',
                'db_table': 'gallery_sections',
                'permissions': (('create_section', 'Can create a new section in the gallery'), ('view_section', 'Can view section in the gallery')),
            },
        ),
    ]
