# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='works.Gallery')),
            ],
            options={
                'verbose_name': 'gallery_section',
                'db_table': 'gallery_sections',
                'verbose_name_plural': 'gallery_sections',
                'permissions': (('create_section', 'Can create a new section in the gallery'), ('view_section', 'Can view section in the gallery')),
            },
        ),
    ]
