# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractPortfolioWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('creation_date', models.DateField(null=True)),
                ('uploaded_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseAudiovisualWork',
            fields=[
                ('abstractportfoliowork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.AbstractPortfolioWork')),
                ('video_url', models.CharField(max_length=255)),
            ],
            bases=('works.abstractportfoliowork',),
        ),
        migrations.CreateModel(
            name='BaseImageWork',
            fields=[
                ('abstractportfoliowork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.AbstractPortfolioWork')),
                ('image_url', models.CharField(max_length=255)),
            ],
            bases=('works.abstractportfoliowork',),
        ),
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('baseimagework_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.BaseImageWork')),
            ],
            options={
                'verbose_name': 'photograph',
                'verbose_name_plural': 'photographs',
                'db_table': 'photograph',
            },
            bases=('works.baseimagework',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('baseaudiovisualwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.BaseAudiovisualWork')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'db_table': 'video',
            },
            bases=('works.baseaudiovisualwork',),
        ),
    ]
