# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 22:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_media_image_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAudiovisualWork',
            fields=[
                ('abstractportfoliowork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.AbstractPortfolioWork')),
                ('video_url', models.CharField(max_length=255)),
            ],
            bases=('works.abstractportfoliowork',),
        ),
        migrations.AlterField(
            model_name='abstractportfoliowork',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 22, 49, 1, 656341), null=True),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('baseaudiovisualwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.BaseAudiovisualWork')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'db_table': 'video',
            },
            bases=('works.baseaudiovisualwork',),
        ),
    ]
