# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerysection',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='works.Gallery'),
        ),
    ]
