# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseaudiovisualwork',
            old_name='video_url',
            new_name='audiovisual_url',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='theme',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='gallerysection',
            old_name='title',
            new_name='theme',
        ),
        migrations.AddField(
            model_name='abstractportfoliowork',
            name='sections',
            field=models.ManyToManyField(to='works.GallerySection'),
        ),
        migrations.AddField(
            model_name='gallerysection',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='works.Gallery'),
        ),
    ]
