# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The initial time the article has been created.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(help_text='The timestamp when the article was first published.', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, help_text='A quick description of the article to make it compelling for other users to read it. Maximum of 255 characters.', max_length=255, null=True),
        ),
    ]
