# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180307_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='main_text',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='Lorem ipsum sit dolor amet.', help_text='Your article content.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Article Title', help_text='A title for the article.', max_length=255),
        ),
    ]
